### ISSUE TITLE
Unable to mint NFT

### ISSUE THREAD

**Issue by wanderer** [attestate/kiwistand#102]
![2023-09-14-124338_grim](https://github.com/attestate/kiwistand/assets/158211/cc126934-37be-49b7-8541-5f9078de8bec)

Looking at the console, this seem relevant. 
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xXXXXX","to":"0xebB15487787cBF8Ae2ffe1a6Cca5a50E63003786","value":{"type":"BigNumber","hex":"0x49d092487f9000"},"data":"0xefef39a10000000000000000000000000000000000000000000000000000000000000001","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0xf12dcc7f"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted\",\n    \"data\": \"0xf12dcc7f\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (

```

## System

Chromium Version 116.0.5845.179 with Metamask

**Comment by TimDaub** [comment]
hey, we disabled the contract today because we're migrating it elsewhere. You'll soon be able to mint again. Sorry for that

**Comment by TimDaub** [comment]
The new mint page is now online and should work with Optimism: https://news.kiwistand.com/welcome 

Keep me posted how it goes, this is pretty fresh off the press

**Comment by TimDaub** [comment]
different metamask error

**Comment by TimDaub** [comment]
closing this as @wanderer and I figured this out
