### ISSUE TITLE
Export theme as env variables

### ISSUE THREAD

**Issue by vrde** [attestate/kiwistand#21]
Right now the theme is managed by a single `THEME` env variable:

https://github.com/attestate/kiwistand/blob/485557293d8f2a6a67167161b1fc646a37e4e02c/src/views/index.mjs#L12-L19

Would be nice to export `color`, `emoji`, and `name` as env variables as well to make it easier to customize the theme without touching the code.

**Comment by TimDaub** [comment]
great idea! Prefixed by THEME_ ideally, THEME_EMOJI

**Comment by TimDaub** [comment]
have this ready in a private branch now
