### ISSUE TITLE
Metamask connection does not work on Arc browser for Desktop

### ISSUE THREAD

**Issue by mattleesounds** [attestate/kiwistand#52]
Arc Version 0.104.0 (38955)
Chromium Engine Version 113.0.5672.126

It acts as if I do not have the Metaask plugin and sends me to the page to download it. Works on normal Chrome browser. 

![Screen Shot 2023-05-24 at 7 29 11 PM](https://github.com/attestate/kiwistand/assets/73853716/340cd47b-8c70-463f-abc0-4e8777a1cdf4)

**Comment by TimDaub** [comment]
thanks for looking into this

we also have problems with Dawn wallet and it seems it is connected to using an outdated version of wagmi or dawn. So I think the way to resolve these issues is by upgrading to wagmi 1.0 and a newer version of connectkit

**Comment by TimDaub** [comment]
<img width="867" alt="Screenshot 2023-07-05 at 17 11 24" src="https://github.com/attestate/kiwistand/assets/2758453/09f943d9-fcf2-4ab2-9cdb-ed6313a42cd5">

this seems to work for me now, if you end up having more problems with this please let me know!
