### ISSUE TITLE
Only cache supported request types

### ISSUE THREAD

**Issue by seeARMS** [attestate/kiwistand#95]
Right now, in `serviveWorker.js` you're trying to cache everything, including PUT and POST requests. Whenever a POST quest occurs there's an error in the console:

```tsx
serviceWorker.js:14 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request method 'POST' is unsupported
    at networkFirst (serviceWorker.js:14:11)
```

Ideally requests like POST/PUT/DELETE (eg ones that mutate) shouldn't be attempted to get cached.

This can likely be fixed by modifying this to check the request type before calling `networkFirst`:

```tsx
self.addEventListener("fetch", (event) => {
  event.respondWith(networkFirst(event.request));
});
```

**Comment by TimDaub** [comment]
thanks for making me aware. However, I now consider touching the service worker API as a mistake. It is sadly designed in a quite dangerous way where one mistake can brick an entire cohorts experience. So I've decided to leave everything as is - and at best install a service worker that'll remove the service working for all existing installed instances.
